version: '3.3'

services:
  db:
    image: postgres:12.8
    restart: always
    ports:
    - 9999:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency