spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:9999/currency
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
